### Importación de datos

In [ ]:
import pandas as pd

url_1 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url_2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url_3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url_4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda_1 = pd.read_csv(url_1)
tienda_2 = pd.read_csv(url_2)
tienda_3 = pd.read_csv(url_3)
tienda_4 = pd.read_csv(url_4)

tienda_1.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [60]:
for i, tienda in enumerate([tienda_1, tienda_2, tienda_3, tienda_4], start=1):
    # Total de ingresos
    total = tienda['Precio'].sum()
    print(f'\n{"="*40}')
    print(f'Tienda {i}')
    print()
    print(f'Ingreso total: ${total:,.2f}')

========================================
Tienda 1

Ingreso total: $1,150,880,400.00

========================================
Tienda 2

Ingreso total: $1,116,343,500.00

========================================
Tienda 3

Ingreso total: $1,098,019,600.00

========================================
Tienda 4

Ingreso total: $1,038,375,700.00

# 2. Ventas por categoría

In [63]:
for i, tienda in enumerate([tienda_1, tienda_2, tienda_3, tienda_4], start=1):
    total = tienda['Precio'].sum()
    print(f'\n{"="*40}')
    print(f'Tienda {i}')
    print()
    print("Productos vendidos por categoría:")
    conteo = tienda['Categoría del Producto'].value_counts()
    for categoria, cantidad in conteo.items():
      print(f'{categoria}: {cantidad}')

========================================
Tienda 1

Productos vendidos por categoría:
Muebles: 465
Electrónicos: 448
Juguetes: 324
Electrodomésticos: 312
Deportes y diversión: 284
Instrumentos musicales: 182
Libros: 173
Artículos para el hogar: 171

========================================
Tienda 2

Productos vendidos por categoría:
Muebles: 442
Electrónicos: 422
Juguetes: 313
Electrodomésticos: 305
Deportes y diversión: 275
Instrumentos musicales: 224
Libros: 197
Artículos para el hogar: 181

========================================
Tienda 3

Productos vendidos por categoría:
Muebles: 499
Electrónicos: 451
Juguetes: 315
Electrodomésticos: 278
Deportes y diversión: 277
Libros: 185
Instrumentos musicales: 177
Artículos para el hogar: 177

========================================
Tienda 4

Productos vendidos por categoría:
Muebles: 480
Electrónicos: 451
Juguetes: 338
Deportes y diversión: 277
Electrodomésticos: 254
Artículos para el hogar: 201
Libros: 187
Instrumentos musicales: 170

# 3. Calificación promedio de la tienda

In [67]:
for i, tienda in enumerate([tienda_1, tienda_2, tienda_3, tienda_4], start=1):
    # Obtener el conteo de productos por categoría
    conteo = tienda['Categoría del Producto'].value_counts()
    print(f'{"="*40}')
    print(f'Tienda {i}')
    print()
    print("Calificación promedio por producto:")
    print()
    promedio_calificaciones = tienda.groupby('Categoría del Producto')['Calificación'].mean()
    for categoria, calificacion_promedio in promedio_calificaciones.items():
        print(f'{categoria}: {calificacion_promedio:.2f}')
        promedio_general = tienda['Calificación'].mean()
    print()
    print(f'Calificación promedio general de la tienda: {promedio_general:.2f}')
    print()

========================================
Tienda 1

Calificación promedio por producto:

Artículos para el hogar: 3.75
Deportes y diversión: 3.90
Electrodomésticos: 4.03
Electrónicos: 4.00
Instrumentos musicales: 4.05
Juguetes: 4.08
Libros: 3.98
Muebles: 3.95

Calificación promedio general de la tienda: 3.98

========================================
Tienda 2

Calificación promedio por producto:

Artículos para el hogar: 4.07
Deportes y diversión: 4.07
Electrodomésticos: 4.07
Electrónicos: 3.97
Instrumentos musicales: 4.04
Juguetes: 4.03
Libros: 3.95
Muebles: 4.09

Calificación promedio general de la tienda: 4.04

========================================
Tienda 3

Calificación promedio por producto:

Artículos para el hogar: 4.07
Deportes y diversión: 3.94
Electrodomésticos: 4.01
Electrónicos: 3.99
Instrumentos musicales: 4.01
Juguetes: 4.20
Libros: 4.05
Muebles: 4.10

Calificación promedio general de la tienda: 4.05

========================================
Tienda 4

Calificación promedio por producto:

Artículos para el hogar: 4.01
Deportes y diversión: 4.05
Electrodomésticos: 3.93
Electrónicos: 4.01
Instrumentos musicales: 3.91
Juguetes: 3.99
Libros: 4.04
Muebles: 4.00

Calificación promedio general de la tienda: 4.00

# 4. Productos más y menos vendidos

In [69]:
for i, tienda in enumerate([tienda_1, tienda_2, tienda_3, tienda_4], start=1):
    conteo = tienda['Categoría del Producto'].value_counts()
    print(f'\n{"="*40}')
    print(f'Tienda {i}')
    print()
    print("\nProductos más y menos vendidos:")
    ventas_por_producto = tienda['Producto'].value_counts()

    producto_mas_vendido = ventas_por_producto.idxmax()
    cantidad_mas_vendida = ventas_por_producto.max()

    producto_menos_vendido = ventas_por_producto.idxmin()
    cantidad_menos_vendida = ventas_por_producto.min()

    print()
    print(f'Más vendido: {producto_mas_vendido} ({cantidad_mas_vendida} ventas)')
    print(f'Menos vendido: {producto_menos_vendido} ({cantidad_menos_vendida} ventas)')

========================================
Tienda 1


Productos más y menos vendidos:

Más vendido: Microondas (60 ventas)
Menos vendido: Auriculares con micrófono (33 ventas)

========================================
Tienda 2


Productos más y menos vendidos:

Más vendido: Iniciando en programación (65 ventas)
Menos vendido: Juego de mesa (32 ventas)

========================================
Tienda 3


Productos más y menos vendidos:

Más vendido: Kit de bancas (57 ventas)
Menos vendido: Bloques de construcción (35 ventas)

========================================
Tienda 4


Productos más y menos vendidos:

Más vendido: Cama box (62 ventas)
Menos vendido: Guitarra eléctrica (33 ventas)

# 5. Envío promedio por tienda

In [71]:
for i, tienda in enumerate([tienda_1, tienda_2, tienda_3, tienda_4], start=1):
    conteo = tienda['Categoría del Producto'].value_counts()
    print(f'\n{"="*40}')
    print(f'Tienda {i}')
    print()
    costo_envio_promedio = tienda['Costo de envío'].mean()
    print(f'Costo de envío promedio de la tienda: ${costo_envio_promedio:.2f}')

========================================
Tienda 1

Costo de envío promedio de la tienda: $26018.61

========================================
Tienda 2

Costo de envío promedio de la tienda: $25216.24

========================================
Tienda 3

Costo de envío promedio de la tienda: $24805.68

========================================
Tienda 4

Costo de envío promedio de la tienda: $23459.46